/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/status": {
    /**
     * Status 
     * @description Verifica se a API está online.
     */
    get: operations["status_api_v1_status_get"];
  };
  "/api/v1/config": {
    /**
     * Get Public Config 
     * @description Retorna configurações públicas da API.
     */
    get: operations["get_public_config_api_v1_config_get"];
  };
  "/api/v1/prices": {
    /**
     * Get Prices 
     * @description Retorna preços históricos para os ativos especificados.
     */
    get: operations["get_prices_api_v1_prices_get"];
    /**
     * Get Prices 
     * @description Retorna preços históricos para os ativos especificados.
     */
    post: operations["get_prices_api_v1_prices_post"];
    /**
     * Options Prices 
     * @description Handles OPTIONS requests for /prices endpoint.
     */
    options: operations["options_prices_api_v1_prices_options"];
  };
  "/api/v1/assets": {
    /**
     * Get Available Assets 
     * @description Retorna a lista de ativos disponíveis com cache HTTP.
     */
    get: operations["get_available_assets_api_v1_assets_get"];
  };
  "/api/v1/ta/moving-averages": {
    /**
     * Ta Moving Averages 
     * @description Calcula médias móveis (SMA ou EMA) para os ativos.
     */
    post: operations["ta_moving_averages_api_v1_ta_moving_averages_post"];
  };
  "/api/v1/ta/macd": {
    /**
     * Ta Macd 
     * @description Calcula MACD (Moving Average Convergence Divergence) para os ativos.
     */
    post: operations["ta_macd_api_v1_ta_macd_post"];
  };
  "/api/v1/risk/ivar": {
    /**
     * Risk Ivar 
     * @description Calcula Incremental VaR (IVaR) - sensibilidade do VaR a mudanças nos pesos.
     */
    post: operations["risk_ivar_api_v1_risk_ivar_post"];
  };
  "/api/v1/risk/mvar": {
    /**
     * Risk Mvar 
     * @description Calcula Marginal VaR (MVaR) - impacto de remover cada ativo da carteira.
     */
    post: operations["risk_mvar_api_v1_risk_mvar_post"];
  };
  "/api/v1/risk/relvar": {
    /**
     * Risk Relative Var 
     * @description Calcula VaR Relativo - risco de underperformance vs benchmark.
     */
    post: operations["risk_relative_var_api_v1_risk_relvar_post"];
  };
  "/api/v1/risk/var": {
    /**
     * Risk Var 
     * @description Calcula Value at Risk (VaR) - métrica de risco de perda máxima esperada.
     */
    post: operations["risk_var_api_v1_risk_var_post"];
  };
  "/api/v1/risk/es": {
    /**
     * Risk Es 
     * @description Calcula Expected Shortfall (ES/CVaR) - perda média além do VaR.
     */
    post: operations["risk_es_api_v1_risk_es_post"];
  };
  "/api/v1/risk/drawdown": {
    /**
     * Risk Drawdown 
     * @description Calcula Maximum Drawdown - maior queda de pico a vale.
     */
    post: operations["risk_drawdown_api_v1_risk_drawdown_post"];
  };
  "/api/v1/risk/stress": {
    /**
     * Risk Stress 
     * @description Simula cenário de stress aplicando choque aos retornos.
     */
    post: operations["risk_stress_api_v1_risk_stress_post"];
  };
  "/api/v1/risk/backtest": {
    /**
     * Risk Backtest 
     * @description Backtest do VaR com testes de Kupiec, Christoffersen e Basel zones.
     */
    post: operations["risk_backtest_api_v1_risk_backtest_post"];
  };
  "/api/v1/risk/montecarlo": {
    /**
     * Risk Montecarlo 
     * @description Simulação Monte Carlo usando Geometric Brownian Motion (GBM).
     */
    post: operations["risk_montecarlo_api_v1_risk_montecarlo_post"];
  };
  "/api/v1/risk/covariance": {
    /**
     * Risk Covariance 
     * @description Calcula matriz de covariância com shrinkage Ledoit-Wolf.
     */
    post: operations["risk_covariance_api_v1_risk_covariance_post"];
  };
  "/api/v1/risk/attribution": {
    /**
     * Risk Attribution 
     * @description Atribuição de risco por ativo (contribuição para volatilidade e VaR).
     */
    post: operations["risk_attribution_api_v1_risk_attribution_post"];
  };
  "/api/v1/risk/compare": {
    /**
     * Risk Compare 
     * @description Compara VaR e ES entre diferentes métodos (historical, std, ewma, garch, evt).
     */
    post: operations["risk_compare_api_v1_risk_compare_post"];
  };
  "/api/v1/risk/drawdown-series": {
    /** Risk Drawdown Series */
    post: operations["risk_drawdown_series_api_v1_risk_drawdown_series_post"];
  };
  "/api/v1/risk/montecarlo/distribution": {
    /** Risk Montecarlo Distribution */
    post: operations["risk_montecarlo_distribution_api_v1_risk_montecarlo_distribution_post"];
  };
  "/api/v1/opt/markowitz": {
    /**
     * Opt Markowitz 
     * @description Otimização de portfólio Markowitz (max Sharpe, min var, max return).
     * 
     * - **risk_free_rate**: Taxa livre de risco anualizada (ex: 0.05 para 5%). 
     *   Se não especificada, usa o valor configurado em `RISK_FREE_RATE`.
     */
    post: operations["opt_markowitz_api_v1_opt_markowitz_post"];
  };
  "/api/v1/opt/blacklitterman": {
    /**
     * Opt Blacklitterman 
     * @description Otimização Black-Litterman com views subjetivas.
     */
    post: operations["opt_blacklitterman_api_v1_opt_blacklitterman_post"];
  };
  "/api/v1/opt/markowitz/frontier-data": {
    /** Frontier Data */
    post: operations["frontier_data_api_v1_opt_markowitz_frontier_data_post"];
  };
  "/api/v1/opt/blacklitterman/frontier-data": {
    /** Bl Frontier Data */
    post: operations["bl_frontier_data_api_v1_opt_blacklitterman_frontier_data_post"];
  };
  "/api/v1/plots/efficient-frontier": {
    /**
     * Plot Efficient Frontier 
     * @description Gera gráfico PNG da fronteira eficiente de Markowitz.
     */
    post: operations["plot_efficient_frontier_api_v1_plots_efficient_frontier_post"];
  };
  "/api/v1/plots/ff-factors": {
    /** Plot Ff Factors Endpoint */
    post: operations["plot_ff_factors_endpoint_api_v1_plots_ff_factors_post"];
  };
  "/api/v1/plots/ff-betas": {
    /** Plot Ff Betas Endpoint */
    post: operations["plot_ff_betas_endpoint_api_v1_plots_ff_betas_post"];
  };
  "/api/v1/plots/ta": {
    /**
     * Plot Technical Analysis 
     * @description Gera gráfico PNG de análise técnica (preços + MAs + MACD).
     */
    post: operations["plot_technical_analysis_api_v1_plots_ta_post"];
  };
  "/api/v1/plots/comprehensive": {
    /**
     * Generate Comprehensive Charts 
     * @description Gera todos os tipos de gráficos disponíveis e salva como arquivos PNG.
     * 
     * Esta funcionalidade combina:
     * - Análise técnica (médias móveis, MACD)
     * - Fatores Fama-French (FF3/FF5) e betas
     * - Fronteira eficiente
     * 
     * Parâmetros:
     *     req: Configurações para geração de gráficos
     *     loader: YFinanceProvider para buscar dados financeiros
     *     config: Configurações da aplicação
     * 
     * Retorna:
     *     ComprehensiveChartsResponse com caminhos dos arquivos gerados
     * 
     * Erros possíveis:
     *     - 422: Dados de entrada inválidos
     *     - 500: Erro interno na geração de gráficos
     *     - 503: Serviço temporariamente indisponível
     */
    post: operations["generate_comprehensive_charts_api_v1_plots_comprehensive_post"];
  };
  "/api/v1/factors/ff3": {
    /**
     * Factors Ff3 
     * @description Calcula métricas Fama-French 3 fatores (mensal) com RF selecionável (SELIC default, US10Y opcional).
     */
    post: operations["factors_ff3_api_v1_factors_ff3_post"];
  };
  "/api/v1/factors/ff5": {
    /**
     * Factors Ff5 
     * @description Calcula métricas Fama-French 5 fatores (mensal): MKT-RF, SMB, HML, RMW, CMA.
     * 
     * RF selecionável: SELIC (padrão) ou US10Y.
     */
    post: operations["factors_ff5_api_v1_factors_ff5_post"];
  };
  "/api/v1/factors/capm": {
    /**
     * Factors Capm 
     * @description Calcula métricas CAPM (beta, alpha, Sharpe) vs benchmark.
     */
    post: operations["factors_capm_api_v1_factors_capm_post"];
  };
  "/api/v1/factors/apt": {
    /**
     * Factors Apt 
     * @description Arbitrage Pricing Theory (APT) - regressão multifatorial.
     */
    post: operations["factors_apt_api_v1_factors_apt_post"];
  };
  "/api/v1/portfolio/weights-series": {
    /** Portfolio Weights Series */
    post: operations["portfolio_weights_series_api_v1_portfolio_weights_series_post"];
  };
  "/api/v1/portfolio/simulate": {
    /**
     * Simulate Portfolio 
     * @description Simulate portfolio performance based on initial investment and trading orders.
     */
    post: operations["simulate_portfolio_api_v1_portfolio_simulate_post"];
  };
  "/api/v1/test-investment": {
    /** Test Investment */
    post: operations["test_investment_api_v1_test_investment_post"];
  };
  "/api/v1/plots/advanced/candlestick": {
    /**
     * Plot Advanced Candlestick 
     * @description Gráfico de candlestick avançado com volume.
     */
    post: operations["plot_advanced_candlestick_api_v1_plots_advanced_candlestick_post"];
  };
  "/api/v1/plots/advanced/price-comparison": {
    /**
     * Plot Price Comparison 
     * @description Comparação de preços de múltiplos ativos.
     */
    post: operations["plot_price_comparison_api_v1_plots_advanced_price_comparison_post"];
  };
  "/api/v1/plots/advanced/risk-metrics": {
    /**
     * Plot Risk Metrics 
     * @description Métricas de risco comparativas.
     */
    post: operations["plot_risk_metrics_api_v1_plots_advanced_risk_metrics_post"];
  };
  "/api/v1/plots/advanced/correlation-heatmap": {
    /**
     * Plot Correlation Heatmap 
     * @description Heatmap de correlação entre ativos.
     */
    post: operations["plot_correlation_heatmap_api_v1_plots_advanced_correlation_heatmap_post"];
  };
  "/api/v1/plots/advanced/return-distribution": {
    /**
     * Plot Return Distribution 
     * @description Distribuição de retornos.
     */
    post: operations["plot_return_distribution_api_v1_plots_advanced_return_distribution_post"];
  };
  "/api/v1/plots/advanced/qq-plot": {
    /**
     * Plot Qq Plot 
     * @description Q-Q plot para verificar normalidade.
     */
    post: operations["plot_qq_plot_api_v1_plots_advanced_qq_plot_post"];
  };
  "/api/v1/plots/advanced/performance-metrics": {
    /**
     * Plot Performance Metrics 
     * @description Métricas de performance comparativas.
     */
    post: operations["plot_performance_metrics_api_v1_plots_advanced_performance_metrics_post"];
  };
  "/api/v1/plots/advanced/efficient-frontier-advanced": {
    /**
     * Plot Efficient Frontier Advanced 
     * @description Fronteira eficiente avançada.
     */
    post: operations["plot_efficient_frontier_advanced_api_v1_plots_advanced_efficient_frontier_advanced_post"];
  };
  "/api/v1/plots/advanced/rolling-beta": {
    /**
     * Plot Rolling Beta Endpoint 
     * @description Plota o beta rolante de um ativo contra um benchmark.
     */
    post: operations["plot_rolling_beta_endpoint_api_v1_plots_advanced_rolling_beta_post"];
  };
  "/api/v1/plots/advanced/underwater": {
    /**
     * Plot Underwater Endpoint 
     * @description Plota o gráfico de drawdown (underwater plot) para um ativo.
     */
    post: operations["plot_underwater_endpoint_api_v1_plots_advanced_underwater_post"];
  };
  "/api/v1/plots/advanced/asset-allocation": {
    /**
     * Plot Asset Allocation Endpoint 
     * @description Gera um gráfico de pizza da alocação de ativos.
     */
    post: operations["plot_asset_allocation_endpoint_api_v1_plots_advanced_asset_allocation_post"];
  };
  "/api/v1/plots/advanced/cumulative-performance": {
    /**
     * Plot Cumulative Performance Endpoint 
     * @description Gera um gráfico de linha da performance acumulada de ativos/portfólio vs. benchmarks.
     */
    post: operations["plot_cumulative_performance_endpoint_api_v1_plots_advanced_cumulative_performance_post"];
  };
  "/api/v1/plots/advanced/risk-contribution": {
    /**
     * Plot Risk Contribution Endpoint 
     * @description Gera um gráfico de barras da contribuição de risco de cada ativo para o portfólio.
     */
    post: operations["plot_risk_contribution_endpoint_api_v1_plots_advanced_risk_contribution_post"];
  };
  "/api/v1/plots/dashboard/sector-analysis": {
    /**
     * Generate Sector Analysis Dashboard 
     * @description Gera um dashboard de análise de setores.
     */
    post: operations["generate_sector_analysis_dashboard_api_v1_plots_dashboard_sector_analysis_post"];
  };
  "/api/v1/plots/dashboard/portfolio": {
    /**
     * Generate Portfolio Dashboard 
     * @description Dashboard completo de portfólio.
     */
    post: operations["generate_portfolio_dashboard_api_v1_plots_dashboard_portfolio_post"];
  };
  "/api/v1/plots/dashboard/risk": {
    /**
     * Generate Risk Dashboard 
     * @description Dashboard focado em análise de risco.
     */
    post: operations["generate_risk_dashboard_api_v1_plots_dashboard_risk_post"];
  };
  "/api/v1/plots/dashboard/performance": {
    /**
     * Generate Performance Dashboard 
     * @description Dashboard focado em performance.
     */
    post: operations["generate_performance_dashboard_api_v1_plots_dashboard_performance_post"];
  };
  "/api/v1/plots/dashboard/monte-carlo": {
    /**
     * Generate Monte Carlo Dashboard 
     * @description Gera um dashboard de simulação Monte Carlo para um portfólio.
     */
    post: operations["generate_monte_carlo_dashboard_api_v1_plots_dashboard_monte_carlo_post"];
  };
  "/api/v1/plots/interactive/candlestick": {
    /**
     * Plot Interactive Candlestick 
     * @description Gráfico de candlestick interativo (JSON).
     */
    post: operations["plot_interactive_candlestick_api_v1_plots_interactive_candlestick_post"];
  };
  "/api/v1/plots/interactive/portfolio-analysis": {
    /**
     * Plot Interactive Portfolio Analysis 
     * @description Análise interativa de portfólio (JSON).
     */
    post: operations["plot_interactive_portfolio_analysis_api_v1_plots_interactive_portfolio_analysis_post"];
  };
  "/api/v1/plots/interactive/efficient-frontier": {
    /**
     * Plot Interactive Efficient Frontier 
     * @description Fronteira eficiente interativa (JSON).
     */
    post: operations["plot_interactive_efficient_frontier_api_v1_plots_interactive_efficient_frontier_post"];
  };
  "/api/v1/plots/interactive/risk-metrics": {
    /**
     * Plot Interactive Risk Metrics 
     * @description Métricas de risco interativas (JSON).
     */
    post: operations["plot_interactive_risk_metrics_api_v1_plots_interactive_risk_metrics_post"];
  };
  "/api/v1/plots/interactive/correlation-matrix": {
    /**
     * Plot Interactive Correlation Matrix 
     * @description Matriz de correlação interativa (JSON).
     */
    post: operations["plot_interactive_correlation_matrix_api_v1_plots_interactive_correlation_matrix_post"];
  };
  "/api/v1/plots/interactive/monte-carlo": {
    /**
     * Plot Interactive Monte Carlo 
     * @description Simulação Monte Carlo interativa (JSON).
     */
    post: operations["plot_interactive_monte_carlo_api_v1_plots_interactive_monte_carlo_post"];
  };
  "/api/v1/analysis/run": {
    /** Run Analysis */
    post: operations["run_analysis_api_v1_analysis_run_post"];
  };
  "/api/v1/processar_operacoes": {
    /** Processar Operacoes */
    post: operations["processar_operacoes_api_v1_processar_operacoes_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** APTRequest */
    APTRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Factors */
      factors: (string)[];
    };
    /** AssetAllocationRequest */
    AssetAllocationRequest: {
      /**
       * Weights 
       * @description Dicionário de ativos e seus pesos no portfólio.
       */
      weights: {
        [key: string]: number | undefined;
      };
      /**
       * Title 
       * @description Título do gráfico. 
       * @default Alocação de Ativos
       */
      title?: string | null;
    };
    /** AttributionRequest */
    AttributionRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Method 
       * @default std 
       * @enum {string}
       */
      method?: "std" | "ewma";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
    };
    /** BLFrontierRequest */
    BLFrontierRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Market Caps */
      market_caps: {
        [key: string]: number | undefined;
      };
      /**
       * Tau 
       * @default 0.05
       */
      tau?: number;
      /**
       * Views 
       * @default []
       */
      views?: ({
          [key: string]: unknown | undefined;
        })[];
      /**
       * N Samples 
       * @default 5000
       */
      n_samples?: number;
      /**
       * Long Only 
       * @default true
       */
      long_only?: boolean;
      /**
       * Max Weight 
       * @description Limite máximo por ativo (0-1)
       */
      max_weight?: number | null;
      /**
       * Rf 
       * @default 0
       */
      rf?: number;
    };
    /** BLRequest */
    BLRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Market Caps */
      market_caps: {
        [key: string]: number | undefined;
      };
      /**
       * Tau 
       * @default 0.05
       */
      tau?: number;
      /**
       * Views 
       * @default []
       */
      views?: ({
          [key: string]: unknown | undefined;
        })[];
    };
    /** BacktestRequest */
    BacktestRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /**
       * Method 
       * @default historical 
       * @enum {string}
       */
      method?: "historical" | "std" | "ewma" | "garch" | "evt";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
    };
    /** Body */
    Body: {
      /** Valorinicial */
      valorInicial: number;
      /** Datainicial */
      dataInicial: string;
      /** Operacoes */
      operacoes: (components["schemas"]["Operacao"])[];
    };
    /** Body_run_analysis_api_v1_analysis_run_post */
    Body_run_analysis_api_v1_analysis_run_post: {
      /** Transactions File */
      transactions_file?: string | null;
    };
    /** CAPMRequest */
    CAPMRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Benchmark 
       * @description Ticker do benchmark ou alias. Aceita: '^GSPC', 'SPY', 'sp500', 's&p500' para S&P500; 'URTH', 'ACWI', 'msci world' para MSCI World.
       */
      benchmark: string;
    };
    /** CompareRequest */
    CompareRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /** Methods */
      methods?: ("historical" | "std" | "ewma" | "garch" | "evt")[];
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
    };
    /** ComprehensiveChartsRequest */
    ComprehensiveChartsRequest: {
      /**
       * Assets 
       * @description Lista de ativos para gerar gráficos
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
      /**
       * Chart Types 
       * @description Tipos de gráficos a gerar
       */
      chart_types?: ("technical_analysis" | "fama_french" | "efficient_frontier")[];
      /**
       * Output Dir 
       * @description Diretório onde salvar os gráficos 
       * @default generated_plots
       */
      output_dir?: string;
      /**
       * Plot Configs 
       * @description Configurações específicas para cada tipo de gráfico
       */
      plot_configs?: ({
        [key: string]: unknown | undefined;
      }) | null;
    };
    /** ComprehensiveChartsResponse */
    ComprehensiveChartsResponse: {
      /**
       * Generated Files 
       * @description Dicionário com caminhos dos arquivos gerados
       */
      generated_files: {
        [key: string]: string | undefined;
      };
      /**
       * Summary 
       * @description Resumo da geração de gráficos
       */
      summary: {
        [key: string]: unknown | undefined;
      };
    };
    /** CumulativePerformanceRequest */
    CumulativePerformanceRequest: {
      /**
       * Assets 
       * @description Lista de tickers dos ativos/portfólio.
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD.
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD.
       */
      end_date: string;
      /**
       * Benchmarks 
       * @description Lista de tickers dos benchmarks para comparação.
       */
      benchmarks?: (string)[] | null;
      /**
       * Title 
       * @description Título do gráfico. 
       * @default Performance Acumulada
       */
      title?: string | null;
    };
    /** DashboardRequest */
    DashboardRequest: {
      /**
       * Assets 
       * @description Lista de ativos para dashboard
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
      /**
       * Title 
       * @description Título do dashboard 
       * @default Financial Dashboard
       */
      title?: string;
      /**
       * Benchmark 
       * @description Ticker do benchmark
       */
      benchmark?: string | null;
      /**
       * Dashboard Type 
       * @description Tipo de dashboard 
       * @default portfolio 
       * @enum {string}
       */
      dashboard_type?: "portfolio" | "risk" | "performance";
    };
    /** DrawdownRequest */
    DrawdownRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
    };
    /** DrawdownSeriesRequest */
    DrawdownSeriesRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
    };
    /** EsRequest */
    EsRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /**
       * Method 
       * @default historical 
       * @enum {string}
       */
      method?: "historical" | "std" | "ewma" | "garch" | "evt";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
    };
    /** FF3Request */
    FF3Request: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Frequency 
       * @default M 
       * @constant
       */
      frequency?: "M";
      /**
       * Market 
       * @default US 
       * @constant
       */
      market?: "US";
      /**
       * Rf Source 
       * @description Fonte do RF: ff (do dataset FF), selic (Brasil) ou us10y (EUA) 
       * @default selic 
       * @enum {string}
       */
      rf_source?: "ff" | "selic" | "us10y";
      /**
       * Convert To Usd 
       * @description Se verdadeiro, converte preços BRL para USD antes da regressão 
       * @default false
       */
      convert_to_usd?: boolean;
    };
    /** FF5Request */
    FF5Request: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Frequency 
       * @default M 
       * @constant
       */
      frequency?: "M";
      /**
       * Market 
       * @default US 
       * @constant
       */
      market?: "US";
      /**
       * Rf Source 
       * @description Fonte do RF: ff (do dataset FF), selic (Brasil) ou us10y (EUA) 
       * @default selic 
       * @enum {string}
       */
      rf_source?: "ff" | "selic" | "us10y";
      /**
       * Convert To Usd 
       * @description Se verdadeiro, converte preços BRL para USD antes da regressão 
       * @default false
       */
      convert_to_usd?: boolean;
    };
    /** FFBetaPlotRequest */
    FFBetaPlotRequest: {
      /**
       * Model 
       * @default ff3 
       * @enum {string}
       */
      model?: "ff3" | "ff5";
      /** Asset */
      asset: string;
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Rf Source 
       * @default selic 
       * @enum {string}
       */
      rf_source?: "ff" | "selic" | "us10y";
      /**
       * Convert To Usd 
       * @description Se verdadeiro, converte o preço do ativo para USD antes da regressão 
       * @default false
       */
      convert_to_usd?: boolean;
    };
    /** FFFactorsPlotRequest */
    FFFactorsPlotRequest: {
      /**
       * Model 
       * @default ff3 
       * @enum {string}
       */
      model?: "ff3" | "ff5";
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
    };
    /** FrontierDataResponse */
    FrontierDataResponse: {
      /** Points */
      points: (components["schemas"]["FrontierPoint"])[];
    };
    /** FrontierPoint */
    FrontierPoint: {
      /** Ret Annual */
      ret_annual: number;
      /** Vol Annual */
      vol_annual: number;
      /** Sharpe */
      sharpe: number;
      /** Weights */
      weights: {
        [key: string]: number | undefined;
      };
    };
    /** FrontierRequest */
    FrontierRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * N Samples 
       * @default 5000
       */
      n_samples?: number;
      /**
       * Long Only 
       * @default true
       */
      long_only?: boolean;
      /**
       * Max Weight 
       * @description Limite máximo por ativo (0-1)
       */
      max_weight?: number | null;
      /**
       * Rf 
       * @default 0
       */
      rf?: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /** HoldingInfo */
    HoldingInfo: {
      /** Asset */
      asset: string;
      /** Quantity */
      quantity: number;
      /** Currentvalue */
      currentValue: number;
      /** Weight */
      weight: number;
      /** Return */
      return_: number;
    };
    /** IVaRRequest */
    IVaRRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /**
       * Method 
       * @default historical 
       * @enum {string}
       */
      method?: "historical" | "std" | "ewma" | "garch" | "evt";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
      /**
       * Delta 
       * @default 0.01
       */
      delta?: number;
    };
    /** InvestmentRequest */
    InvestmentRequest: {
      /** Assets */
      assets: (string)[];
      /** Weights */
      weights: (number)[];
      /** Period */
      period: string;
    };
    /** MVaRRequest */
    MVaRRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /**
       * Method 
       * @default historical 
       * @enum {string}
       */
      method?: "historical" | "std" | "ewma" | "garch" | "evt";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
    };
    /** MonteCarloDashboardRequest */
    MonteCarloDashboardRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * N Paths 
       * @description Número de caminhos de simulação 
       * @default 1000
       */
      n_paths?: number;
      /**
       * N Days 
       * @description Número de dias para simulação 
       * @default 252
       */
      n_days?: number;
      /**
       * Vol Method 
       * @default std 
       * @enum {string}
       */
      vol_method?: "std" | "ewma" | "garch";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
      /** Seed */
      seed?: number | null;
    };
    /** MonteCarloRequest */
    MonteCarloRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * N Paths 
       * @default 10000
       */
      n_paths?: number;
      /**
       * N Days 
       * @default 252
       */
      n_days?: number;
      /**
       * Vol Method 
       * @default std 
       * @enum {string}
       */
      vol_method?: "std" | "ewma" | "garch";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
      /** Seed */
      seed?: number | null;
    };
    /** MonteCarloSamplesRequest */
    MonteCarloSamplesRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * N Paths 
       * @default 10000
       */
      n_paths?: number;
      /**
       * N Days 
       * @default 252
       */
      n_days?: number;
      /**
       * Vol Method 
       * @default std 
       * @enum {string}
       */
      vol_method?: "std" | "ewma" | "garch";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
      /** Seed */
      seed?: number | null;
      /**
       * Return Type 
       * @default histogram 
       * @enum {string}
       */
      return_type?: "histogram" | "samples";
      /**
       * Bins 
       * @default 50
       */
      bins?: number;
    };
    /** Operacao */
    Operacao: {
      /** Data */
      data: string;
      /** Ticker */
      ticker: string;
      /** Tipo */
      tipo: string;
      /** Valor */
      valor: number;
    };
    /** OptimizeRequest */
    OptimizeRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /**
       * Objective 
       * @default max_sharpe 
       * @enum {string}
       */
      objective?: "max_sharpe" | "min_var" | "max_return";
      /**
       * Long Only 
       * @default true
       */
      long_only?: boolean;
      /** Max Weight */
      max_weight?: number | null;
      /** Bounds */
      bounds?: ((unknown)[])[] | null;
      /**
       * Risk Free Rate 
       * @description Taxa livre de risco anualizada (ex: 0.05 para 5%). Se não especificada, usa o valor da configuração.
       */
      risk_free_rate?: number | null;
    };
    /**
     * OrderType 
     * @enum {string}
     */
    OrderType: "BUY" | "SELL";
    /** PortfolioPerformance */
    PortfolioPerformance: {
      /** Totalreturn */
      totalReturn: number;
      /** Annualizedreturn */
      annualizedReturn: number;
      /** Maxdrawdown */
      maxDrawdown: number;
      /** Volatility */
      volatility: number;
      /** Sharperatio */
      sharpeRatio: number;
    };
    /** PortfolioSimulationRequest */
    PortfolioSimulationRequest: {
      /** Initialinvestment */
      initialInvestment: number;
      /**
       * Startdate 
       * Format: date
       */
      startDate: string;
      /**
       * Enddate 
       * Format: date
       */
      endDate: string;
      /** Orders */
      orders: (components["schemas"]["TradeOrder"])[];
    };
    /** PortfolioSimulationResponse */
    PortfolioSimulationResponse: {
      /** Portfoliovalue */
      portfolioValue: (components["schemas"]["PortfolioValue"])[];
      performance: components["schemas"]["PortfolioPerformance"];
      /** Holdings */
      holdings: (components["schemas"]["HoldingInfo"])[];
      /** Transactions */
      transactions: (components["schemas"]["TradeOrder"])[];
    };
    /** PortfolioValue */
    PortfolioValue: {
      /**
       * Date 
       * Format: date
       */
      date: string;
      /** Value */
      value: number;
    };
    /** PricesRequest */
    PricesRequest: {
      /**
       * Assets 
       * @description Lista de tickers, ex.: ['PETR4.SA','VALE3.SA']
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
    };
    /** PricesResponse */
    PricesResponse: {
      /** Columns */
      columns: (string)[];
      /** Index */
      index: (string)[];
      /** Data */
      data: ((number)[])[];
    };
    /** RelVaRRequest */
    RelVaRRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /**
       * Method 
       * @default historical 
       * @enum {string}
       */
      method?: "historical" | "std" | "ewma" | "garch" | "evt";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
      /**
       * Benchmark 
       * @description Ticker do benchmark ou alias (ex.: '^GSPC'/'SPY'/'sp500' para S&P500; 'URTH'/'ACWI'/'msci world' para MSCI World).
       */
      benchmark: string;
    };
    /** RiskContributionRequest */
    RiskContributionRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Method 
       * @default std 
       * @enum {string}
       */
      method?: "std" | "ewma";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
      /**
       * Title 
       * @description Título do gráfico. 
       * @default Contribuição de Risco por Ativo
       */
      title?: string | null;
    };
    /** RiskResponse */
    RiskResponse: {
      /** Result */
      result: {
        [key: string]: unknown | undefined;
      };
    };
    /** RollingBetaRequest */
    RollingBetaRequest: {
      /**
       * Asset 
       * @description Ticker do ativo principal
       */
      asset: string;
      /**
       * Benchmark 
       * @description Ticker do benchmark (ex: '^BVSP')
       */
      benchmark: string;
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
      /**
       * Window 
       * @description Janela rolante em dias para o cálculo do beta 
       * @default 60
       */
      window?: number;
    };
    /** SectorAnalysisRequest */
    SectorAnalysisRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
    };
    /** StressRequest */
    StressRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Shock Pct 
       * @description Choque percentual aplicado ao último retorno diário 
       * @default -0.1
       */
      shock_pct?: number;
    };
    /** TAMacdRequest */
    TAMacdRequest: {
      /**
       * Assets 
       * @description Lista de tickers, ex.: ['PETR4.SA','VALE3.SA']
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
      /**
       * Fast 
       * @default 12
       */
      fast?: number;
      /**
       * Slow 
       * @default 26
       */
      slow?: number;
      /**
       * Signal 
       * @default 9
       */
      signal?: number;
      /**
       * Include Original 
       * @default true
       */
      include_original?: boolean;
      /** Only Columns */
      only_columns?: (string)[] | null;
    };
    /** TAMovingAveragesRequest */
    TAMovingAveragesRequest: {
      /**
       * Assets 
       * @description Lista de tickers, ex.: ['PETR4.SA','VALE3.SA']
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
      /**
       * Method 
       * @default sma 
       * @enum {string}
       */
      method?: "sma" | "ema";
      /** Windows */
      windows?: (number)[];
      /**
       * Include Original 
       * @default true
       */
      include_original?: boolean;
      /** Only Columns */
      only_columns?: (string)[] | null;
    };
    /** TAPlotRequest */
    TAPlotRequest: {
      /**
       * Asset 
       * @description Ticker do ativo para gerar o gráfico
       */
      asset: string;
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
      /**
       * Plot Type 
       * @default combined 
       * @enum {string}
       */
      plot_type?: "ma" | "macd" | "combined";
      /** Ma Windows */
      ma_windows?: (number)[];
      /**
       * Ma Method 
       * @default sma 
       * @enum {string}
       */
      ma_method?: "sma" | "ema";
      /**
       * Macd Fast 
       * @default 12
       */
      macd_fast?: number;
      /**
       * Macd Slow 
       * @default 26
       */
      macd_slow?: number;
      /**
       * Macd Signal 
       * @default 9
       */
      macd_signal?: number;
    };
    /** TimeSeriesResponse */
    TimeSeriesResponse: {
      /** Index */
      index: (string)[];
      /** Data */
      data: (number)[];
    };
    /** TradeOrder */
    TradeOrder: {
      /** Asset */
      asset: string;
      type: components["schemas"]["OrderType"];
      /** Quantity */
      quantity: number;
      /**
       * Date 
       * Format: date
       */
      date: string;
      /** Price */
      price?: number | null;
    };
    /** UnderwaterPlotRequest */
    UnderwaterPlotRequest: {
      /**
       * Assets 
       * @description Lista de tickers, ex.: ['PETR4.SA','VALE3.SA']
       */
      assets: (string)[];
      /**
       * Start Date 
       * @description Data inicial no formato YYYY-MM-DD
       */
      start_date: string;
      /**
       * End Date 
       * @description Data final no formato YYYY-MM-DD
       */
      end_date: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VarRequest */
    VarRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Alpha 
       * @default 0.99
       */
      alpha?: number;
      /**
       * Method 
       * @default historical 
       * @enum {string}
       */
      method?: "historical" | "std" | "ewma" | "garch" | "evt";
      /**
       * Ewma Lambda 
       * @default 0.94
       */
      ewma_lambda?: number;
    };
    /** WeightsSeriesRequest */
    WeightsSeriesRequest: {
      /** Assets */
      assets: (string)[];
      /** Start Date */
      start_date: string;
      /** End Date */
      end_date: string;
      /** Weights */
      weights?: (number)[] | null;
      /**
       * Strategy 
       * @default buy_and_hold 
       * @constant
       */
      strategy?: "buy_and_hold";
    };
    /** WeightsSeriesResponse */
    WeightsSeriesResponse: {
      /** Index */
      index: (string)[];
      /** Weights */
      weights: {
        [key: string]: (number)[] | undefined;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * Status 
   * @description Verifica se a API está online.
   */
  status_api_v1_status_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string | undefined;
          };
        };
      };
      /** @description Not found */
      404: never;
    };
  };
  /**
   * Get Public Config 
   * @description Retorna configurações públicas da API.
   */
  get_public_config_api_v1_config_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown | undefined;
          };
        };
      };
      /** @description Not found */
      404: never;
    };
  };
  /**
   * Get Prices 
   * @description Retorna preços históricos para os ativos especificados.
   */
  get_prices_api_v1_prices_get: {
    parameters: {
      query: {
        assets?: string;
        start_date?: string;
        end_date?: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PricesResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Prices 
   * @description Retorna preços históricos para os ativos especificados.
   */
  get_prices_api_v1_prices_post: {
    parameters: {
      query: {
        assets?: string;
        start_date?: string;
        end_date?: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PricesResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Options Prices 
   * @description Handles OPTIONS requests for /prices endpoint.
   */
  options_prices_api_v1_prices_options: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
    };
  };
  /**
   * Get Available Assets 
   * @description Retorna a lista de ativos disponíveis com cache HTTP.
   */
  get_available_assets_api_v1_assets_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
    };
  };
  /**
   * Ta Moving Averages 
   * @description Calcula médias móveis (SMA ou EMA) para os ativos.
   */
  ta_moving_averages_api_v1_ta_moving_averages_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TAMovingAveragesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PricesResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Ta Macd 
   * @description Calcula MACD (Moving Average Convergence Divergence) para os ativos.
   */
  ta_macd_api_v1_ta_macd_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TAMacdRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PricesResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Ivar 
   * @description Calcula Incremental VaR (IVaR) - sensibilidade do VaR a mudanças nos pesos.
   */
  risk_ivar_api_v1_risk_ivar_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["IVaRRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Mvar 
   * @description Calcula Marginal VaR (MVaR) - impacto de remover cada ativo da carteira.
   */
  risk_mvar_api_v1_risk_mvar_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MVaRRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Relative Var 
   * @description Calcula VaR Relativo - risco de underperformance vs benchmark.
   */
  risk_relative_var_api_v1_risk_relvar_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelVaRRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Var 
   * @description Calcula Value at Risk (VaR) - métrica de risco de perda máxima esperada.
   */
  risk_var_api_v1_risk_var_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VarRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Es 
   * @description Calcula Expected Shortfall (ES/CVaR) - perda média além do VaR.
   */
  risk_es_api_v1_risk_es_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Drawdown 
   * @description Calcula Maximum Drawdown - maior queda de pico a vale.
   */
  risk_drawdown_api_v1_risk_drawdown_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DrawdownRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Stress 
   * @description Simula cenário de stress aplicando choque aos retornos.
   */
  risk_stress_api_v1_risk_stress_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StressRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Backtest 
   * @description Backtest do VaR com testes de Kupiec, Christoffersen e Basel zones.
   */
  risk_backtest_api_v1_risk_backtest_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BacktestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Montecarlo 
   * @description Simulação Monte Carlo usando Geometric Brownian Motion (GBM).
   */
  risk_montecarlo_api_v1_risk_montecarlo_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MonteCarloRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Covariance 
   * @description Calcula matriz de covariância com shrinkage Ledoit-Wolf.
   */
  risk_covariance_api_v1_risk_covariance_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VarRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Attribution 
   * @description Atribuição de risco por ativo (contribuição para volatilidade e VaR).
   */
  risk_attribution_api_v1_risk_attribution_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttributionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Risk Compare 
   * @description Compara VaR e ES entre diferentes métodos (historical, std, ewma, garch, evt).
   */
  risk_compare_api_v1_risk_compare_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompareRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Risk Drawdown Series */
  risk_drawdown_series_api_v1_risk_drawdown_series_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DrawdownSeriesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TimeSeriesResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Risk Montecarlo Distribution */
  risk_montecarlo_distribution_api_v1_risk_montecarlo_distribution_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MonteCarloSamplesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Opt Markowitz 
   * @description Otimização de portfólio Markowitz (max Sharpe, min var, max return).
   * 
   * - **risk_free_rate**: Taxa livre de risco anualizada (ex: 0.05 para 5%). 
   *   Se não especificada, usa o valor configurado em `RISK_FREE_RATE`.
   */
  opt_markowitz_api_v1_opt_markowitz_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OptimizeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Opt Blacklitterman 
   * @description Otimização Black-Litterman com views subjetivas.
   */
  opt_blacklitterman_api_v1_opt_blacklitterman_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BLRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Frontier Data */
  frontier_data_api_v1_opt_markowitz_frontier_data_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FrontierRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FrontierDataResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Bl Frontier Data */
  bl_frontier_data_api_v1_opt_blacklitterman_frontier_data_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BLFrontierRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FrontierDataResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Efficient Frontier 
   * @description Gera gráfico PNG da fronteira eficiente de Markowitz.
   */
  plot_efficient_frontier_api_v1_plots_efficient_frontier_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FrontierRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Plot Ff Factors Endpoint */
  plot_ff_factors_endpoint_api_v1_plots_ff_factors_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FFFactorsPlotRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Plot Ff Betas Endpoint */
  plot_ff_betas_endpoint_api_v1_plots_ff_betas_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FFBetaPlotRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Technical Analysis 
   * @description Gera gráfico PNG de análise técnica (preços + MAs + MACD).
   */
  plot_technical_analysis_api_v1_plots_ta_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TAPlotRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Comprehensive Charts 
   * @description Gera todos os tipos de gráficos disponíveis e salva como arquivos PNG.
   * 
   * Esta funcionalidade combina:
   * - Análise técnica (médias móveis, MACD)
   * - Fatores Fama-French (FF3/FF5) e betas
   * - Fronteira eficiente
   * 
   * Parâmetros:
   *     req: Configurações para geração de gráficos
   *     loader: YFinanceProvider para buscar dados financeiros
   *     config: Configurações da aplicação
   * 
   * Retorna:
   *     ComprehensiveChartsResponse com caminhos dos arquivos gerados
   * 
   * Erros possíveis:
   *     - 422: Dados de entrada inválidos
   *     - 500: Erro interno na geração de gráficos
   *     - 503: Serviço temporariamente indisponível
   */
  generate_comprehensive_charts_api_v1_plots_comprehensive_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComprehensiveChartsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ComprehensiveChartsResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Factors Ff3 
   * @description Calcula métricas Fama-French 3 fatores (mensal) com RF selecionável (SELIC default, US10Y opcional).
   */
  factors_ff3_api_v1_factors_ff3_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FF3Request"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Factors Ff5 
   * @description Calcula métricas Fama-French 5 fatores (mensal): MKT-RF, SMB, HML, RMW, CMA.
   * 
   * RF selecionável: SELIC (padrão) ou US10Y.
   */
  factors_ff5_api_v1_factors_ff5_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FF5Request"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Factors Capm 
   * @description Calcula métricas CAPM (beta, alpha, Sharpe) vs benchmark.
   */
  factors_capm_api_v1_factors_capm_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CAPMRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Factors Apt 
   * @description Arbitrage Pricing Theory (APT) - regressão multifatorial.
   */
  factors_apt_api_v1_factors_apt_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["APTRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RiskResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Portfolio Weights Series */
  portfolio_weights_series_api_v1_portfolio_weights_series_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WeightsSeriesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WeightsSeriesResponse"];
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Simulate Portfolio 
   * @description Simulate portfolio performance based on initial investment and trading orders.
   */
  simulate_portfolio_api_v1_portfolio_simulate_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSimulationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioSimulationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Test Investment */
  test_investment_api_v1_test_investment_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvestmentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Advanced Candlestick 
   * @description Gráfico de candlestick avançado com volume.
   */
  plot_advanced_candlestick_api_v1_plots_advanced_candlestick_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Price Comparison 
   * @description Comparação de preços de múltiplos ativos.
   */
  plot_price_comparison_api_v1_plots_advanced_price_comparison_post: {
    parameters: {
      query: {
        normalize?: boolean;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Risk Metrics 
   * @description Métricas de risco comparativas.
   */
  plot_risk_metrics_api_v1_plots_advanced_risk_metrics_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Correlation Heatmap 
   * @description Heatmap de correlação entre ativos.
   */
  plot_correlation_heatmap_api_v1_plots_advanced_correlation_heatmap_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Return Distribution 
   * @description Distribuição de retornos.
   */
  plot_return_distribution_api_v1_plots_advanced_return_distribution_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Qq Plot 
   * @description Q-Q plot para verificar normalidade.
   */
  plot_qq_plot_api_v1_plots_advanced_qq_plot_post: {
    parameters: {
      query: {
        asset: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Performance Metrics 
   * @description Métricas de performance comparativas.
   */
  plot_performance_metrics_api_v1_plots_advanced_performance_metrics_post: {
    parameters: {
      query: {
        benchmark?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Efficient Frontier Advanced 
   * @description Fronteira eficiente avançada.
   */
  plot_efficient_frontier_advanced_api_v1_plots_advanced_efficient_frontier_advanced_post: {
    parameters: {
      query: {
        n_portfolios?: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Rolling Beta Endpoint 
   * @description Plota o beta rolante de um ativo contra um benchmark.
   */
  plot_rolling_beta_endpoint_api_v1_plots_advanced_rolling_beta_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RollingBetaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Underwater Endpoint 
   * @description Plota o gráfico de drawdown (underwater plot) para um ativo.
   */
  plot_underwater_endpoint_api_v1_plots_advanced_underwater_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnderwaterPlotRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Asset Allocation Endpoint 
   * @description Gera um gráfico de pizza da alocação de ativos.
   */
  plot_asset_allocation_endpoint_api_v1_plots_advanced_asset_allocation_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetAllocationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Cumulative Performance Endpoint 
   * @description Gera um gráfico de linha da performance acumulada de ativos/portfólio vs. benchmarks.
   */
  plot_cumulative_performance_endpoint_api_v1_plots_advanced_cumulative_performance_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CumulativePerformanceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Risk Contribution Endpoint 
   * @description Gera um gráfico de barras da contribuição de risco de cada ativo para o portfólio.
   */
  plot_risk_contribution_endpoint_api_v1_plots_advanced_risk_contribution_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RiskContributionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Sector Analysis Dashboard 
   * @description Gera um dashboard de análise de setores.
   */
  generate_sector_analysis_dashboard_api_v1_plots_dashboard_sector_analysis_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SectorAnalysisRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Portfolio Dashboard 
   * @description Dashboard completo de portfólio.
   */
  generate_portfolio_dashboard_api_v1_plots_dashboard_portfolio_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DashboardRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Risk Dashboard 
   * @description Dashboard focado em análise de risco.
   */
  generate_risk_dashboard_api_v1_plots_dashboard_risk_post: {
    parameters: {
      query: {
        var_alpha?: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DashboardRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Performance Dashboard 
   * @description Dashboard focado em performance.
   */
  generate_performance_dashboard_api_v1_plots_dashboard_performance_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DashboardRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Monte Carlo Dashboard 
   * @description Gera um dashboard de simulação Monte Carlo para um portfólio.
   */
  generate_monte_carlo_dashboard_api_v1_plots_dashboard_monte_carlo_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MonteCarloDashboardRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Interactive Candlestick 
   * @description Gráfico de candlestick interativo (JSON).
   */
  plot_interactive_candlestick_api_v1_plots_interactive_candlestick_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Interactive Portfolio Analysis 
   * @description Análise interativa de portfólio (JSON).
   */
  plot_interactive_portfolio_analysis_api_v1_plots_interactive_portfolio_analysis_post: {
    parameters: {
      query: {
        benchmark?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Interactive Efficient Frontier 
   * @description Fronteira eficiente interativa (JSON).
   */
  plot_interactive_efficient_frontier_api_v1_plots_interactive_efficient_frontier_post: {
    parameters: {
      query: {
        n_portfolios?: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Interactive Risk Metrics 
   * @description Métricas de risco interativas (JSON).
   */
  plot_interactive_risk_metrics_api_v1_plots_interactive_risk_metrics_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Interactive Correlation Matrix 
   * @description Matriz de correlação interativa (JSON).
   */
  plot_interactive_correlation_matrix_api_v1_plots_interactive_correlation_matrix_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Plot Interactive Monte Carlo 
   * @description Simulação Monte Carlo interativa (JSON).
   */
  plot_interactive_monte_carlo_api_v1_plots_interactive_monte_carlo_post: {
    parameters: {
      query: {
        asset: string;
        n_simulations?: number;
        n_days?: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PricesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Not found */
      404: never;
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Run Analysis */
  run_analysis_api_v1_analysis_run_post: {
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_run_analysis_api_v1_analysis_run_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Processar Operacoes */
  processar_operacoes_api_v1_processar_operacoes_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
