import pytest
import schemathesis
from schemathesis.core import NotSet
from fastapi import FastAPI
from starlette.testclient import TestClient
from pathlib import Path
import os

# Assuming your FastAPI app is in backend_projeto.main
# You might need to adjust the import path based on your project structure
from backend_projeto.main import app

# Path to your OpenAPI schema file
# It's generated in packages/backend/openapi.json
OPENAPI_SCHEMA_PATH = Path(__file__).parent.parent / "openapi.json"

# Ensure the OpenAPI schema file exists
if not OPENAPI_SCHEMA_PATH.exists():
    raise FileNotFoundError(f"OpenAPI schema file not found at {OPENAPI_SCHEMA_PATH}")

# Load the OpenAPI schema
schema = schemathesis.openapi.from_path(str(OPENAPI_SCHEMA_PATH))

@pytest.fixture(scope="module")
def test_client():
    """Provides a TestClient for the FastAPI application."""
    # Disable raise_server_exceptions so internal errors return 500 instead of raising
    with TestClient(app, raise_server_exceptions=False) as client:
        yield client


def _is_valid_status(status_code: int) -> bool:
    """
    Check if a response status code is valid.
    
    We accept:
    - 2xx: Success responses
    - 400: Bad Request (invalid parameters)
    - 401, 403, 404, 405: Standard error responses
    - 422: Validation errors (Pydantic may reject edge cases that OpenAPI allows)
    - 5xx: Server errors
    """
    return (
        200 <= status_code < 300 or
        status_code in (400, 401, 403, 404, 405, 422) or
        500 <= status_code < 600
    )


@schema.parametrize()
def test_api_schema(case, test_client):
    """
    Validate API endpoints against the OpenAPI schema using Schemathesis.
    This test generates requests based on the schema and validates responses.
    
    Note: Schemathesis generates edge cases (e.g., empty lists for arrays) that
    are technically schema-valid but semantically invalid. Our Pydantic validators
    correctly reject these with 422 responses, which we consider acceptable.
    """
    # Handle NotSet values from schemathesis - these can't be JSON serialized
    body = case.body if not isinstance(case.body, NotSet) else None
    headers = case.headers if not isinstance(case.headers, NotSet) else None
    params = case.query if not isinstance(case.query, NotSet) else None
    
    # Execute the request generated by Schemathesis
    response = test_client.request(
        method=case.method,
        url=case.path,
        headers=headers,
        json=body,
        params=params,
    )
    
    # Custom validation: Accept 422 as valid since our Pydantic validators
    # are stricter than what the OpenAPI schema expresses (e.g., minItems)
    assert _is_valid_status(response.status_code), (
        f"Unexpected status code {response.status_code} for {case.method} {case.path}. "
        f"Response: {response.text[:500]}"
    )

# You can add more specific tests here if needed,
# for example, testing specific endpoints with known valid/invalid data
# or testing authentication flows.
