import pytest
import schemathesis
from fastapi import FastAPI
from starlette.testclient import TestClient
from pathlib import Path
import os

# Assuming your FastAPI app is in src.backend_projeto.main
# You might need to adjust the import path based on your project structure
from src.backend_projeto.main import app

# Path to your OpenAPI schema file
# It's generated in packages/backend/openapi.json
OPENAPI_SCHEMA_PATH = Path(__file__).parent.parent / "openapi.json"

# Ensure the OpenAPI schema file exists
if not OPENAPI_SCHEMA_PATH.exists():
    raise FileNotFoundError(f"OpenAPI schema file not found at {OPENAPI_SCHEMA_PATH}")

# Load the OpenAPI schema
schema = schemathesis.openapi.from_path(str(OPENAPI_SCHEMA_PATH))

@pytest.fixture(scope="module")
def test_client():
    """Provides a TestClient for the FastAPI application."""
    with TestClient(app) as client:
        yield client

@schema.parametrize()
def test_api_schema(case, test_client):
    """
    Validate API endpoints against the OpenAPI schema using Schemathesis.
    This test generates requests based on the schema and validates responses.
    """
    # Execute the request generated by Schemathesis
    response = test_client.request(
        method=case.method,
        url=case.path,
        headers=case.headers,
        json=case.body,
        params=case.query,
    )

    # Validate the response against the OpenAPI schema
    case.validate_response(response)

# You can add more specific tests here if needed,
# for example, testing specific endpoints with known valid/invalid data
# or testing authentication flows.
