# Domain module exports
# Domain-Driven Design structure

# NOTE: DDD components (value_objects, entities, repositories, services) 
# are imported directly when needed to avoid circular imports.
# Example: from backend_projeto.domain.value_objects import Money

# Legacy exports (for backward compatibility - these have existing dependencies)
from .analysis import (
    _as_weights,
    compute_returns,
    portfolio_returns,
    calculate_rolling_beta,
    var_parametric,
    es_parametric,
    var_historical,
    es_historical,
    var_evt,
    es_evt,
    drawdown,
    stress_test,
    backtest_var,
    covariance_ledoit_wolf,
    risk_attribution,
    incremental_var,
    marginal_var,
    relative_var,
    ff3_metrics,
    ff5_metrics,
    RiskEngine,
    PortfolioAnalyzer,
)
from .exceptions import (
    AppError,
    DataProviderError,
    InvalidTransactionFileError,
    DataValidationError,
)
from .financial_math import _returns_from_prices, _annualize_mean_cov
from .optimization import OptimizationEngine
from .simulation import MonteCarloEngine
from .technical_analysis import moving_averages, macd, macd_series
from .trading_calendar import trading_calendar
from .models.models import (
    ApiErrorResponse,
    PricesRequest,
    PricesResponse,
    FF3Request,
    FF5Request,
    CAPMRequest,
    APTRequest,
    OptimizeRequest,
    BLRequest,
    FrontierRequest,
    BLFrontierRequest,
    RiskResponse,
    AttributionRequest,
    CompareRequest,
    TAMovingAveragesRequest,
    TAMacdRequest,
    IVaRRequest,
    MVaRRequest,
    RelVaRRequest,
    TAPlotRequest,
    FFFactorsPlotRequest,
    FFBetaPlotRequest,
    WeightsSeriesRequest,
    WeightsSeriesResponse,
    DrawdownSeriesRequest,
    TimeSeriesResponse,
    FrontierDataResponse,
    FrontierPoint,
    ComprehensiveChartsRequest,
    ComprehensiveChartsResponse,
    AdvancedChartRequest,
    DashboardRequest,
    InteractiveChartRequest,
    RollingBetaRequest,
    UnderwaterPlotRequest,
    SectorAnalysisRequest,
    MonteCarloDashboardRequest,
    AssetAllocationRequest,
    CumulativePerformanceRequest,
    RiskContributionRequest,
    VarRequest,
    EsRequest,
    MonteCarloRequest,
    MonteCarloSamplesRequest,
    BacktestRequest,
    DrawdownRequest,
    StressRequest,
)
from .models.portfolio_simulation import (
    PortfolioSimulationRequest,
    PortfolioSimulationResponse,
    PortfolioValue,
    HoldingInfo,
    PortfolioPerformance,
    TradeOrder,
)

__all__ = [
    "_as_weights",
    "compute_returns",
    "portfolio_returns",
    "calculate_rolling_beta",
    "var_parametric",
    "es_parametric",
    "var_historical",
    "es_historical",
    "var_evt",
    "es_evt",
    "drawdown",
    "stress_test",
    "backtest_var",
    "covariance_ledoit_wolf",
    "risk_attribution",
    "incremental_var",
    "marginal_var",
    "relative_var",
    "ff3_metrics",
    "ff5_metrics",
    "RiskEngine",
    "PortfolioAnalyzer",
    "AppError",
    "DataProviderError",
    "InvalidTransactionFileError",
    "DataValidationError",
    "_returns_from_prices",
    "_annualize_mean_cov",
    "OptimizationEngine",
    "MonteCarloEngine",
    "moving_averages",
    "macd",
    "macd_series",
    "trading_calendar",
    "ApiErrorResponse",
    "PricesRequest",
    "PricesResponse",
    "FF3Request",
    "FF5Request",
    "CAPMRequest",
    "APTRequest",
    "OptimizeRequest",
    "BLRequest",
    "FrontierRequest",
    "BLFrontierRequest",
    "RiskResponse",
    "AttributionRequest",
    "CompareRequest",
    "TAMovingAveragesRequest",
    "TAMacdRequest",
    "IVaRRequest",
    "MVaRRequest",
    "RelVaRRequest",
    "TAPlotRequest",
    "FFFactorsPlotRequest",
    "FFBetaPlotRequest",
    "WeightsSeriesRequest",
    "WeightsSeriesResponse",
    "DrawdownSeriesRequest",
    "TimeSeriesResponse",
    "FrontierDataResponse",
    "FrontierPoint",
    "ComprehensiveChartsRequest",
    "ComprehensiveChartsResponse",
    "AdvancedChartRequest",
    "DashboardRequest",
    "InteractiveChartRequest",
    "RollingBetaRequest",
    "UnderwaterPlotRequest",
    "SectorAnalysisRequest",
    "MonteCarloDashboardRequest",
    "AssetAllocationRequest",
    "CumulativePerformanceRequest",
    "RiskContributionRequest",
    "VarRequest",
    "EsRequest",
    "MonteCarloRequest",
    "MonteCarloSamplesRequest",
    "BacktestRequest",
    "DrawdownRequest",
    "StressRequest",
    "PortfolioSimulationRequest",
    "PortfolioSimulationResponse",
    "PortfolioValue",
    "HoldingInfo",
    "PortfolioPerformance",
    "TradeOrder",
]